### ISSUE TITLE
bug: Predefined split requires control_code

### ISSUE THREAD

**Issue by kirilklein** [kirilklein/corebehrt_phair#97]

**Comment by kirilklein** [comment]
Traceback (most recent call last):
  File "ehr2vec/main/04_finetune_cv.py", line 213, in <module>
    data = dataset_preparer.prepare_finetune_data()
  File "/mnt/azureml/cr/j/c3834e2a3fd34eb0aa7c2b31bd7033f8/exe/wd/ehr2vec/data/prepare_data.py", line 152, in prepare_finetune_data
    control_code = self.cfg.outcome.control_code
AttributeError: 'Config' object has no attribute 'control_code'
